### ISSUE TITLE
Do you have live example of you plugin,

### ISSUE THREAD

**Issue by syedbaqarrizvi** [gkralik/videojs-shaka-tech#1]
Actually i have a wordpress plugin i was just trying to implement it in my wordpress plugin but the index file is not working in the code pen after adding all files . 
if you have any example in codepen please let me know 

Thanks

**Comment by gkralik** [comment]
Show me what you tried.

**Comment by syedbaqarrizvi** [comment]
http://codepen.io/baqarrizvi/pen/XdEwYR?editors=1000

**Comment by gkralik** [comment]
So what's your problem? The above pen works just fine for me.
