### ISSUE TITLE
TypeError: Cannot read property 'Player' of undefined

### ISSUE THREAD

**Issue by netwrkx** [gkralik/videojs-shaka-tech#2]
videojs-shaka-tech.js:54 Uncaught TypeError: Cannot read property 'Player' of undefined

source code
    <script src="../dist/video.js"></script>
    <script src="../dist/shaka-player.compiled.js"></script>
    <script src="../dist/videojs-shaka-tech.js"></script>

package.json
    "video.js": "^5.11.9",
    "shaka-player": "2.0.8",

**Comment by gkralik** [comment]
This repository is unmaintained. I do not use the plugin anymore. You are welcome to fix the problem and submit a PR though.
